name: Release Tag to Production
on:
  push:
    tags:
      - v*.**
jobs:
  deploy-production:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Merge main back to release
        run: |
            git fetch --unshallow
            git checkout release
            git pull
            git merge --no-ff ${GITHUB_SHA} -m "Auto-merge main to release branch"
      - name: Deploy to Production (Amplify)
        run: |
            curl -X POST -d {} "${{ secrets.DEPLOYMENT_WEBHOOK_URL }}" -H "Content-Type:application/json"
