name: Release Tag to Production
on:
  push:
    tags:
      - v*.**
jobs:
  release-and-deploy-production:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Push tagged release to release branch
        run: |
            git fetch --unshallow
            git checkout release
            git pull
            git merge --no-ff ${GITHUB_SHA} -m "Merging commit ${GITHUB_SHA} from main: ${{ github.event.head_commit.message }}"
            git push
